[2025-01-13T16:10:05.475+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T16:10:05.488+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:09:00+00:00 [queued]>
[2025-01-13T16:10:05.497+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:09:00+00:00 [queued]>
[2025-01-13T16:10:05.499+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-13T16:10:05.511+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): append_to_database> on 2025-01-13 16:09:00+00:00
[2025-01-13T16:10:05.517+0000] {standard_task_runner.py:72} INFO - Started process 2587 to run task
[2025-01-13T16:10:05.520+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'append_to_database', 'scheduled__2025-01-13T16:09:00+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmplgitt5p9']
[2025-01-13T16:10:05.523+0000] {standard_task_runner.py:105} INFO - Job 407: Subtask append_to_database
[2025-01-13T16:10:05.562+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.append_to_database scheduled__2025-01-13T16:09:00+00:00 [running]> on host 453ac4defedc
[2025-01-13T16:10:05.642+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='append_to_database' AIRFLOW_CTX_EXECUTION_DATE='2025-01-13T16:09:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-13T16:09:00+00:00'
[2025-01-13T16:10:05.644+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T16:10:05.695+0000] {logging_mixin.py:190} INFO - Kết nối thành công!
[2025-01-13T16:10:05.697+0000] {logging_mixin.py:190} INFO - Có lỗi khi thực hiện append_database: The second parameter to executemany must be a sequence, iterator, or generator.
[2025-01-13T16:10:05.700+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-13T16:10:05.711+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T16:10:05.713+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_information, task_id=append_to_database, run_id=scheduled__2025-01-13T16:09:00+00:00, execution_date=20250113T160900, start_date=20250113T161005, end_date=20250113T161005
[2025-01-13T16:10:05.735+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-13T16:10:05.753+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T16:10:05.758+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
