[2025-01-11T06:09:02.497+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-11T06:09:02.510+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api scheduled__2025-01-11T06:08:00+00:00 [queued]>
[2025-01-11T06:09:02.518+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_information.stream_data_from_api scheduled__2025-01-11T06:08:00+00:00 [queued]>
[2025-01-11T06:09:02.520+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-11T06:09:02.532+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-01-11 06:08:00+00:00
[2025-01-11T06:09:02.538+0000] {standard_task_runner.py:72} INFO - Started process 408 to run task
[2025-01-11T06:09:02.540+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'stock_information', 'stream_data_from_api', 'scheduled__2025-01-11T06:08:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/vnstock_stream.py', '--cfg-path', '/tmp/tmp2l28teq5']
[2025-01-11T06:09:02.543+0000] {standard_task_runner.py:105} INFO - Job 259: Subtask stream_data_from_api
[2025-01-11T06:09:02.582+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_information.stream_data_from_api scheduled__2025-01-11T06:08:00+00:00 [running]> on host 453ac4defedc
[2025-01-11T06:09:02.654+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='TuanDz' AIRFLOW_CTX_DAG_ID='stock_information' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-01-11T06:08:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-11T06:08:00+00:00'
[2025-01-11T06:09:02.656+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-11T06:09:02.984+0000] {data_explorer.py:64} WARNING - Thông tin niêm yết & giao dịch sẽ được truy xuất từ TCBS
[2025-01-11T06:09:03.337+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/vnstock_stream.py", line 51, in get_current_price
    price_df = get_price_board(stock_code)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/vnstock_stream.py", line 68, in get_price_board
    price_board['last_update']= to_pydatetime(datetime.now())
                                ^^^^^^^^^^^^^
NameError: name 'to_pydatetime' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/vnstock_stream.py", line 53, in get_current_price
    error_log_save( err_file_path, f'get_current_price() {e}')
  File "/opt/airflow/dags/vnstock_stream.py", line 36, in error_log_save
    f.write(time() + ' :' + err)
            ~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for +: 'float' and 'str'
[2025-01-11T06:09:03.367+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=stock_information, task_id=stream_data_from_api, run_id=scheduled__2025-01-11T06:08:00+00:00, execution_date=20250111T060800, start_date=20250111T060902, end_date=20250111T060903
[2025-01-11T06:09:03.383+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-11T06:09:03.385+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 259 for task stream_data_from_api (unsupported operand type(s) for +: 'float' and 'str'; 408)
Traceback (most recent call last):
  File "/opt/airflow/dags/vnstock_stream.py", line 51, in get_current_price
    price_df = get_price_board(stock_code)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/vnstock_stream.py", line 68, in get_price_board
    price_board['last_update']= to_pydatetime(datetime.now())
                                ^^^^^^^^^^^^^
NameError: name 'to_pydatetime' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/vnstock_stream.py", line 53, in get_current_price
    error_log_save( err_file_path, f'get_current_price() {e}')
  File "/opt/airflow/dags/vnstock_stream.py", line 36, in error_log_save
    f.write(time() + ' :' + err)
            ~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for +: 'float' and 'str'
[2025-01-11T06:09:03.401+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-11T06:09:03.418+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-11T06:09:03.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
